MODEL="Qwen/Qwen2-7B"
TARGET_LANG="cmn_Hans"
SAVE_FOLDER="../artifacts/qwen2.5-7b/data-single_prompt-zero_hidden-base-mean_hidden-target-mean_cmn/"
DATA="single"
PROMPT="zero"
HIDDEN_BASE="mean"
HIDDEN_TARGET="mean"