MODEL="Qwen/Qwen2-1.5B"
TARGET_LANG="cmn_Hans"
SAVE_FOLDER="../artifacts/qwen2.5-1.5b/data-full_prompt-zero_hidden-base-mean_hidden-target-mean_cmn/"
DATA="full"
PROMPT="zero"
HIDDEN_BASE="mean"
HIDDEN_TARGET="mean"