MODEL="/home/khanh/sla/sla_cpt/qwen2.5-0.5b_english_wiki_irish_corpus_custom_sampler/"
TARGET_LANG="gle_Latn"
SAVE_FOLDER="../artifacts/qwen2.5-0.5b_english_wiki_irish_corpus_custom_sampler/data-full_prompt-zero_hidden-base-mean_hidden-target-mean_gle/"
DATA="full"
PROMPT="zero"
HIDDEN_BASE="mean"
HIDDEN_TARGET="mean"