MODEL="ReliableAI/UCCIX-Llama2-13B"
TARGET_LANG="gle_Latn"
SAVE_FOLDER="../artifacts/uccix-llama2-13b/data-full_prompt-zero_hidden-base-mean_hidden-target-mean_gle/"
DATA="full"
PROMPT="zero"
HIDDEN_BASE="mean"
HIDDEN_TARGET="mean"